### ISSUE TITLE
Add SALT encoding and decoding

### ISSUE THREAD

**Issue by BurnySc2** [BurnySc2/sc2-planner#1]
Insert it here:
https://github.com/BurnySc2/sc2-planner/blob/f806961a366e7b1a71702a5a48e043a5513a2b87/src/constants/helper.js#L182-L188
Use file /constants/salt_constants.js

References:
https://drive.google.com/file/d/0Bzrw_bC8iBjfSzFRRGlWWnNWNDg/view
https://github.com/Veritasimo/sc2-scrapbook/blob/68028fdbc7ce67a394ba139746e82485ebbf4312/SALT.cs#L150
https://www.reddit.com/r/starcraft/comments/25losh/build_order_tool_salt_update/chin15d/

Edit: Alternatively it could be done parsing the text of the spawningtool build order output by https://github.com/StoicLoofah/spawningtool

**Comment by BurnySc2** [comment]
Closing in favor of issue https://github.com/BurnySc2/sc2-planner/issues/9
SALT encoding does contain less information than sc2-planner build orders - technically it could be exported as SALT encoding, but that seems a lot of work for now.
Importing from SALT encoding will lack information, so that would be fairly pointless.

Importing from replays would provide complete information.

**Comment by DejayRezme** [comment]
This tool looks really awesome! 

But I was about to ask if it is possible to export to salt to practice a build order with a mod.  Maybe that is just me, returning after long time and trying to get into sc2 and totally fumbling. The EMBOT advanced mod is pretty nice, but I assume the copy paste SALT is just too limited in length? The SCV/drone building are basically implied by the supply because of this I think. Is this technically just not really possible with a better encoding?

Or is there a mod where I can copy paste the build order from SC2 planner into?

Or maybe one could export and save a new mod or map with a collection of SC2 Planner build orders to practice. I guess that would definitely be possible, but a bit cumbersome turnaround time from planner to practice.

PS: Now I wonder if you could even implement SC2 Planner as a UI mod or map so you can plan your builds ingame and then test them, but that would of course be way too much work. Just thinking out loud haha.
