### ISSUE TITLE
Import button is broken

### ISSUE THREAD

**Issue by Volker-Weissmann** [BurnySc2/sc2-planner#10]
If I click on the import button on "https://burnysc2.github.io/sc2-planner/",  nothing happens.
Firefox 78.0

**Comment by BurnySc2** [comment]
The import button has no functionality at the moment. I have disabled it in https://github.com/BurnySc2/sc2-planner/commit/d0176ab1669c6cd645f4e6a843746c4e1be62d1d to avoid further confusion.

Suggestions for import functionality are listed here https://github.com/BurnySc2/sc2-planner/issues/9 and here https://github.com/BurnySc2/sc2-planner/issues/1
However, both are a little bit difficult to implement - my typescript skills are probably not good enough so that it requires an external python script or even server where you can upload replays to, and get a `.json` file back which can then be imported by sc2-planner.
