### ISSUE TITLE
Cannot undo 

### ISSUE THREAD

**Issue by LHarriger** [BurnySc2/sc2-planner#2]
https://burnysc2.github.io/sc2-planner/?&race=terran&bo=uDritmrisSJEritSf2HtL2NtZU2HsMN2PtkuBtgV2KritnfibViriuFsExaGsJRxaJtjkilTkli2MxdIx3axaasKzADyUzsKIzO9yUTxZJtR3QtZfe07KsLxbKyuT1cKtleZkx2KsQzm1sLx32xaasJzmKyU9xaKzoK06NsMxXJtR3otZfe0cKxZRtNuF

Try removing the "return worker scout" or "worker scout" icon. It looks like if you do stack these in the wrong order, then you cannot unstack them

**Comment by BurnySc2** [comment]
Thanks for the find! I'll look at it when I wake up tomorrow.

**Comment by BurnySc2** [comment]
Since the images of the `worker scout` and `worker return` are quite small, the `on click` functionality was only working if you clicked directly on the image, instead of the whole box. It is working now for the whole box. Fixed in https://github.com/BurnySc2/sc2-planner/commit/cf58aca608cb1b9c44d00160dd438c2af83f499e

Feel free to keep reporting bugs that you find.
