### ISSUE TITLE
Chrono issue

### ISSUE THREAD

**Issue by Anish-Reddy** [BurnySc2/sc2-planner#7]
Can't chrono several buildings like fleet beacon, robo bay, robo facility etc.

**Comment by Anish-Reddy** [comment]
Just realized this is a duplicate lol

**Comment by BurnySc2** [comment]
I was thinking of leaving out fleet beacon, dark shrine, robo bay from the list of available chronos (because I don't think they are going to be part of any build order - maybe chrono colossus range for a 2 base colossus timing?) but I will definitely add robo facility and twilight.

Or do you think it makes sense to include those first three, too, just for the sake of completeness?

**Comment by jtsauls** [comment]
Probably go for completeness, because people may use your tool to figure out weird things like "how fast can I get to DT blink." Maybe add drop down if it's too cluttered.
